server:
    port: ${PORT:9050}

eureka:
    instance:
            statusPageUrlPath: ${management.contextPath}/info
            healthCheckUrlPath: ${management.contextPath}/health
    client:
        serviceUrl:
            defaultZone: ${eureka.uri:http://127.0.0.1:9010}/eureka/,${eureka.uri:http://127.0.0.1:9011}/eureka/
spring:
    boot:
        admin:
            url: http://localhost:${server.port}
management:
    contextPath: /management