server:
    port: ${PORT:9020}
spring:
    boot:
        admin:
            url: http://localhost:9000
eureka:
    client:
        serviceUrl:
            defaultZone: ${eureka.uri:http://127.0.0.1:9010}/eureka/
            
management:
    contextPath: /management