server:
    port: ${PORT:9020}
spring:
    boot:
        admin:
            url: http://localhost:9050
eureka:
    instance:
            statusPageUrlPath: ${management.contextPath}/info
            healthCheckUrlPath: ${management.contextPath}/health
    client:
        serviceUrl:
            defaultZone: ${eureka1.uri:http://127.0.0.1:9010}/eureka/,${eureka2.uri:http://127.0.0.1:9011}/eureka/
            
management:
    contextPath: /management