--- 
spring:
    profiles: peer1

server:
    port: ${PORT:9010}

management:
    contextPath: /management

eureka:
    instance:
        statusPageUrlPath: ${management.contextPath}/info
        healthCheckUrlPath: ${management.contextPath}/health
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        serviceUrl:
            defaultZone: ${eureka.uri:http://127.0.0.1:9011}/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0 

--- 
spring:
    profiles: peer2

server:
    port: ${PORT:9011}

management:
    contextPath: /management

eureka:
    instance:
        statusPageUrlPath: ${management.contextPath}/info
        healthCheckUrlPath: ${management.contextPath}/health
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        serviceUrl:
            defaultZone: ${eureka.uri:http://127.0.0.1:9010}/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0