server:
    port: ${PORT:9070}
spring:
    boot:
        admin:
            url: http://localhost:9050

    datasource
        url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username=sa
        password=
    jpa
        database-platform:org.hibernate.dialect.H2Dialect

eureka:
    instance:
            statusPageUrlPath: ${management.contextPath}/info
            healthCheckUrlPath: ${management.contextPath}/health
    client:
        serviceUrl:
            defaultZone: ${eureka.uri:http://127.0.0.1:9010}/eureka/,${eureka.uri:http://127.0.0.1:9011}/eureka/
            
management:
    contextPath: /management
